/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string>
/* Header for class com_nd_lib_NdUitilityJni */

#ifndef _Included_com_nd_lib_NdSmsUtilsjni
#define _Included_com_nd_lib_NdSmsUtilsjni

#ifdef __cplusplus
extern "C" {
#endif

	extern JavaVM *gJavaVM;

	bool androidSendSms(std::string strMsg, std::string strTels);


#ifdef __cplusplus
}
#endif


#endif