//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由Codesmith工具生成。
// 此文件的更改可能会导致不正确的行为，如果
// 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using ProtoBuf;
using ZyGames.Framework.Common;
using ZyGames.Framework.Collection;
using ZyGames.Framework.Model;


namespace GameNotice.Model
{
    /// <summary>
    /// 
    /// </summary>
    /// <![CDATA[
    /// @periodTime:设置生存周期(秒)
    /// @personalName: 映射UserId对应的字段名,默认为"UserId"
    /// ]]>
    /// </remarks>
    [Serializable, ProtoContract]
    [EntityTable(CacheType.Entity, "GameData", "Notice")]
    public class Notice :  ShareEntity
    {

        /// <summary>
        /// </summary>
        public Notice()
            : base(AccessLevel.ReadWrite)
        {
        }        
        /// <summary>
        /// </summary>
        public Notice(int id)
            : this()
        {
            _id = id;
        }

        #region 自动生成属性
        private int _id;
        /// <summary>
        /// 
        /// </summary>        
        [ProtoMember(1)]
        [EntityField("Id", IsKey = true)]
        public int Id
        {
            get
            {
                return _id;
            } 
            
        }
        private string _title;
        /// <summary>
        /// 
        /// </summary>        
        [ProtoMember(2)]
        [EntityField("Title")]
        public string Title
        {
            get
            {
                return _title;
            } 
            set
            {
                SetChange("Title", value);
            }
        }
        private string _content;
        /// <summary>
        /// 
        /// </summary>        
        [ProtoMember(3)]
        [EntityField("Content")]
        public string Content
        {
            get
            {
                return _content;
            } 
            set
            {
                SetChange("Content", value);
            }
        }
        private DateTime _createDate;
        /// <summary>
        /// 
        /// </summary>        
        [ProtoMember(4)]
        [EntityField("CreateDate")]
        public DateTime CreateDate
        {
            get
            {
                return _createDate;
            } 
            set
            {
                SetChange("CreateDate", value);
            }
        }
    
        protected override object this[string index]
		{
			get
			{
                #region
				switch (index)
				{
                    case "Id": return _id;
                    case "Title": return _title;
                    case "Content": return _content;
                    case "CreateDate": return _createDate;
					default: throw new ArgumentException(string.Format("Notice index[{0}] isn't exist.", index));
				}
                #endregion
			}
			set
			{
                #region
				switch (index)
				{
                    case "Id": 
                        _id = value.ToInt();
                        break; 
                    case "Title": 
                        _title = value.ToNotNullString();
                        break; 
                    case "Content": 
                        _content = value.ToNotNullString();
                        break; 
                    case "CreateDate": 
                        _createDate = value.ToDateTime();
                        break; 
					default: throw new ArgumentException(string.Format("Notice index[{0}] isn't exist.", index));
				}
                #endregion
			}
		}
        
        #endregion
        

	}
}